### ISSUE TITLE
Drawer issues when selecting polymorphism class in Unity 2022.3.0f1

### ISSUE THREAD

**Issue by Agnate** [AlexeyTaranov/SerializeReferenceDropdown#15]
Hi, I was excited to find this library but I'm having an issue. Seems on Unity 2022.3.0f1 I can't get the dropdown option I select to show up. I can see my polymorphism class in the dropdown when I put my array in a ScriptableObject:

![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/659758/975b1a83-68dc-482c-9d4c-d5192b4425d0)

But after I select it a class, I just get a null entry:

![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/659758/6a7418d1-a5c6-4d66-a66e-306bd58e2b4f)

I tried recreating the example you had (IShape, Circle, Rectangle, add an array to a MonoBehaviour), but it produced the same results.

However, I noticed something. When I recreated your example in a new project, I could get the item to appear correctly after adding a second item to my array.

Empty list:
![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/659758/d5417946-6483-4734-91db-f088022d9efb)

Add a Rectangle:
![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/659758/4b1ec37b-bc5c-4fd3-93bd-3f27c92c21ea)

Shows as null:
![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/659758/8acd2168-dc66-4bdb-9033-f2002532893a)

Click the Add button and it appears:
![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/659758/7fce9eb2-4b2e-4e41-9591-5a4f47ec01d2)

**Comment by AlexeyTaranov** [comment]
@Agnate Is it windows os editor? Can you test on 2022.3.4?
Can you test this on IMGUI inspector? Edit -> Project Settings -> Editor -> Use IMGUI Default Inspector
It is only ui elements inspector problem?
Unfortunately, I only have macos editor and can't reproduce this bug(

**Comment by Agnate** [comment]
Yep that seems to fix it! Thanks.

**Comment by AlexeyTaranov** [comment]
@Agnate Hi. Fixed bug on 0.3.4. version package
